### ISSUE TITLE
the game is giving error (definition.csv) line 83

### ISSUE THREAD

**Issue by gabrielsky211** [marxistguy/Victoria-II-Ultimate-Ultimatum#2]

**Comment by marxman1412** [comment]
either try changing the line in the .mod file from 

name = "Ultimate Ultimatum"
path = "mod/Ultimate Ultimatum"
user_dir = "Ultimate Ultimatum" 

to 

name = "Ultimate Ultimatum v1.0 beta"
path = "mod/Ultimate Ultimatum v1.0 beta"
user_dir = "Ultimate Ultimatum v1.0 beta" 

or simply change the line in default.map from

definitions = "../mod/Ultimate Ultimatum v1.0 beta/map/definition.csv"

to definitions = "../mod/Ultimate Ultimatum/map/definition.csv"

**Comment by gabrielsky211** [comment]
recommend you put later in moddb if you go to post version 1.0 the github link so it is easier for other people to know that you are alive as well as report problems like this (if and that people report pq I'm not American just got into github because of you so do not know if people use this function )

**Comment by marxman1412** [comment]
curently i rather keep this version to myself and those who found it, still a long way to a full 1.0 release that is why i use github to host it for now. but if you want to give feedbacks just keep giving me issues, I'll try my best addressing it

**Comment by gabrielsky211** [comment]
man i would love to help you so if you want help you can email me with some problems you found in the mod so maybe i can help you solve them

then I kind of send them back and you review what you think?

**Comment by marxman1412** [comment]
sure thing, just send me anything, any kind of help is welcome and appreciated :)

**Comment by gabrielsky211** [comment]
look due to my lack of time I do not sure if I can do much more what I see error I will send you I will try to help you although this next year I will have much less time than I had before (which was already little 2h free on the day) 

so if I disappear it was because of that "life and sad :("
